// <auto-generated />
using System;
using Envoy.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Envoy.Core.Data.Migrations
{
    [DbContext(typeof(EnvoyDbContext))]
    partial class EnvoyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Envoy.Core.Models.ApplicationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AfterScreenshot")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("BeforeScreenshot")
                        .HasColumnType("BLOB");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TailoredProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("Envoy.Core.Models.MasterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ParseConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MasterProfiles");
                });

            modelBuilder.Entity("Envoy.Core.Models.TailoredProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangesMade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescriptionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterProfileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SafetyResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TailoredData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TailoredProfiles");
                });

            modelBuilder.Entity("Envoy.Core.Models.MasterProfile", b =>
                {
                    b.OwnsMany("Envoy.Core.Models.EducationEntry", "Education", b1 =>
                        {
                            b1.Property<Guid>("MasterProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Degree")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("GraduationDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Institution")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Location")
                                .HasColumnType("TEXT");

                            b1.HasKey("MasterProfileId", "Id");

                            b1.ToTable("EducationEntry");

                            b1.WithOwner()
                                .HasForeignKey("MasterProfileId");
                        });

                    b.OwnsMany("Envoy.Core.Models.ExperienceEntry", "Experience", b1 =>
                        {
                            b1.Property<Guid>("MasterProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bullets")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndDate")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsCurrent")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("JobTitle")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Location")
                                .HasColumnType("TEXT");

                            b1.Property<string>("StartDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("MasterProfileId", "Id");

                            b1.ToTable("ExperienceEntry");

                            b1.WithOwner()
                                .HasForeignKey("MasterProfileId");
                        });

                    b.OwnsMany("Envoy.Core.Models.ProjectEntry", "Projects", b1 =>
                        {
                            b1.Property<Guid>("MasterProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Technologies")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MasterProfileId", "Id");

                            b1.ToTable("ProjectEntry");

                            b1.WithOwner()
                                .HasForeignKey("MasterProfileId");
                        });

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
